### ISSUE TITLE
Point spread function reconstruction metadata PSFR

### ISSUE THREAD

**Issue by zonca** [oirlab/iris_metadata#1]
From @edwardchapin:

> Not sure how you want to handle it, but somewhere in this spreadsheet you should mention that we have a new requirement in the AOESW-IRIS ICD about the PSF Reconstructor providing all of the PSFR data to the IRIS DRS. This isn't included in model files because it is expected that the PSFR data will be stored in the DMS, and IRIS DRS will get the data from there.

In the master spreadsheet, https://github.com/oirlab/iris_metadata#master-sheet-on-google, we don't track any of this.
@edwardchapin is there a document that explains this in detail?

**Comment by edwardchapin** [comment]
Other than the details which appear in the AOESW-NFIRAOS ICD, and the new requirement I've proposed for the AOESW-IRIS ICD, there is no other document (if you recall a few weeks ago I suggested creating a new document to use as a "cheat sheet" for all of this IRIS DRS metadata, but then it seemed more appropriate to add here somehow). I'm open to suggestions. Maybe a separate document on TMT DCC with a document number that can be references is the way to go.

**Comment by zonca** [comment]
ok, thanks, I cannot find on docushare the AOESW-NFIRAOS ICD, can you point me to that?

**Comment by edwardchapin** [comment]
The AOESW-NFIRAOS ICD updates are only in draft form at the moment... I'll send it to you in an email.

**Comment by zonca** [comment]
from the document it seems like there is yet no details on what "raw data" from the Adaptive Optics will be required by IRIS for PSF reconstruction. Without more details, the spreadsheet is not suitable.
Probably we want to have a section in the DSR design document explaining this.

**Comment by edwardchapin** [comment]
That sounds sensible. I think you really need AO / PSF experts to figure this all out (it seems to be a bit of a black art...), and the intention with the ICD change was just to ensure that the TMT AO group is aware of the formal need for PSF reconstruction information by IRIS, with details TBD. A section in the DRS doc is perfect.

**Comment by zonca** [comment]
ok I added this paragraph to the "PSF-reconstruction" section of the DRS design doc, will gather feedback also from Shelley and Arun:

>The DRS will need raw data from the Adaptive Optics system to perform PSF reconstruction, the amount of data required is too large to be transferred as standard telemetry and will require a dedicated system implemented into the Data Management System (not available yet). For this reason the metadata necessary for PSF-reconstruciton are not mentioned in the ICD between the AO system and the DRS.

**Comment by edwardchapin** [comment]
In addition to "...not mentioned in the ICD between the AO system and the DRS", I would also add "nor the ICD between IRIS and the DRS" (since that is ultimately where DRS will be getting the data).

**Comment by zonca** [comment]
ok, got feedback from @arunsurya77 offline, added @edwardchapin's clarification to the design document.
